# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_yys_win(object):
    def setupUi(self, yys_win):
        yys_win.setObjectName("yys_win")
        yys_win.setEnabled(True)
        yys_win.resize(467, 585)
        self.centralwidget = QtWidgets.QWidget(yys_win)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 444, 541))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_0 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_0.setObjectName("horizontalLayout_0")
        # label_adb
        self.label_adb = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_adb.setObjectName("label_adb")
        self.horizontalLayout_0.addWidget(self.label_adb)

        self.adb_port = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.adb_port.setObjectName("adb_port")
        self.horizontalLayout_0.addWidget(self.adb_port)

        # label_window
        self.label_window = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_window.setObjectName("label_window")
        self.horizontalLayout_0.addWidget(self.label_window)

        self.window_name = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.window_name.setObjectName("window_name")
        self.horizontalLayout_0.addWidget(self.window_name)

        self.verticalLayout.addLayout(self.horizontalLayout_0)

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        # label
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        # 功能选择
        self.cb_fuctions = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cb_fuctions.setObjectName("cb_fuctions")
        self.horizontalLayout_2.addWidget(self.cb_fuctions)
        # 显示设置
        self.pbt_autocheck = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pbt_autocheck.setObjectName("pbt_autocheck")
        self.horizontalLayout_2.addWidget(self.pbt_autocheck)
        # 重新启动
        self.pbt_restart = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pbt_restart.setObjectName("pbt_restart")
        self.horizontalLayout_2.addWidget(self.pbt_restart)
        # 启动
        self.pbt_start = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pbt_start.setObjectName("pbt_start")
        self.horizontalLayout_2.addWidget(self.pbt_start)
        # 结束
        self.pbt_end = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pbt_end.setObjectName("push_end")
        self.horizontalLayout_2.addWidget(self.pbt_end)

        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem)

        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        self.cb_p1 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cb_p1.setObjectName("cb_p1")
        self.horizontalLayout_3.addWidget(self.cb_p1)

        self.cb_p2 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cb_p2.setObjectName("cb_p2")
        self.horizontalLayout_3.addWidget(self.cb_p2)

        self.cb_p3 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cb_p3.setObjectName("cb_p3")
        self.horizontalLayout_3.addWidget(self.cb_p3)

        self.cb_p4 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cb_p4.setObjectName("cb_p4")
        self.horizontalLayout_3.addWidget(self.cb_p4)

        self.verticalLayout.addLayout(self.horizontalLayout_3)
        #信息展示区
        self.pte_msg = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.pte_msg.setReadOnly(True)
        self.pte_msg.setObjectName("pte_msg")
        self.verticalLayout.addWidget(self.pte_msg)
        #清楚信息按钮
        self.ptn_clear = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ptn_clear.setObjectName("ptn_clear")
        self.verticalLayout.addWidget(self.ptn_clear)
        
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem1)
        # 左侧
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        # 左侧-信息提示区
        self.te_attention = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.te_attention.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.te_attention.setObjectName("te_attention")
        self.horizontalLayout.addWidget(self.te_attention)
        # 右侧
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        # 右侧-顶部提示
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        # 右侧-下面二维码
        self.lb_qrcode = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lb_qrcode.setMaximumSize(QtCore.QSize(100, 100))
        self.lb_qrcode.setScaledContents(True)
        self.lb_qrcode.setObjectName("lb_qrcode")
        self.verticalLayout_2.addWidget(self.lb_qrcode)
        
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        yys_win.setCentralWidget(self.centralwidget)

        self.retranslateUi(yys_win)
        self.pbt_start.clicked.connect(yys_win.btn_start_clicked)
        self.pbt_end.clicked.connect(yys_win.btn_stop_clicked)
        self.cb_fuctions.currentIndexChanged['QString'].connect(yys_win.cb_functions_index_changed)
        self.ptn_clear.clicked.connect(self.pte_msg.clear)
        self.pbt_restart.clicked.connect(yys_win.btn_restart_clicked)
        QtCore.QMetaObject.connectSlotsByName(yys_win)

    def retranslateUi(self, yys_win):
        _translate = QtCore.QCoreApplication.translate
        yys_win.setWindowTitle(_translate("yys_win", "yys-辅助工具"))
        self.label_adb.setText(_translate('yys_win', "模拟器ADB端口："))
        self.label_window.setText(_translate('yys_win', "模拟器名称："))
        self.label.setText(_translate("yys_win", "功能："))
        self.cb_fuctions.setItemText(0, _translate("yys_win", "御魂"))
        self.cb_fuctions.setItemText(1, _translate("yys_win", "困28"))
        self.cb_fuctions.setItemText(2, _translate("yys_win", "御灵"))
        self.cb_fuctions.setItemText(3, _translate("yys_win", "业原火"))
        self.cb_fuctions.setItemText(4, _translate("yys_win", "结界突破"))
        self.pbt_autocheck.setText(_translate("yys_win", "设置参数"))
        self.pbt_restart.setText(_translate("yys_win", "重新开始"))
        self.pbt_start.setText(_translate("yys_win", "开始"))
        self.pbt_end.setText(_translate("yys_win", "结束"))
        self.cb_p1.setItemText(0, _translate("yys_win", "单人"))
        self.cb_p1.setItemText(1, _translate("yys_win", "组队"))

        self.cb_p2.setItemText(0, _translate("yys_win", "队长"))
        self.cb_p2.setItemText(1, _translate("yys_win", "队员"))

        self.cb_p3.setItemText(0, _translate("yys_win", "挂机次数"))
        self.cb_p3.setItemText(1, _translate("yys_win", "30"))
        self.cb_p3.setItemText(2, _translate("yys_win", "50"))
        self.cb_p3.setItemText(3, _translate("yys_win", "120"))
        self.cb_p3.setItemText(4, _translate("yys_win", "999"))

        self.cb_p4.setItemText(0, _translate("yys_win", "魂十"))
        self.cb_p4.setItemText(1, _translate("yys_win", "魂十一"))

        self.pte_msg.setPlainText(_translate("yys_win", "执行日志："))
        self.ptn_clear.setText(_translate("yys_win", "清空日志"))
